import { currentApproval, elapsedHours, hireAtRisk, hireReadiness, taskBlocked, taskOverdue, TEAM_NAMES } from "./analytics";
import type { WorkspacePayload } from "./types";

type Cell = string | number | boolean | null;
type Row = Record<string, Cell>;
export const SNAPSHOT_TABLES = ["hires", "tasks", "teams", "review_episodes", "approval_history", "metadata"] as const;
export type SnapshotTable = typeof SNAPSHOT_TABLES[number];

export function validatePowerBiUrl(raw: string | null | undefined, mode: "public" | "secure"): { url: string | null; error: string | null } {
  if (!raw?.trim()) return { url: null, error: null };
  try {
    const url = new URL(raw.trim());
    if (url.protocol !== "https:" || url.hostname !== "app.powerbi.com" || url.port || url.username || url.password || url.hash)
      throw new Error("Use an HTTPS embed URL generated by Power BI on app.powerbi.com.");
    if ([...url.searchParams.keys()].some((key) => url.searchParams.getAll(key).length !== 1))
      throw new Error("The embed URL contains duplicate parameters; copy the generated iframe source again.");
    if (mode === "public") {
      if (url.pathname !== "/view" || !url.searchParams.get("r") || !/^[A-Za-z0-9_+/=-]+$/.test(url.searchParams.get("r")!))
        throw new Error("Public mode requires Microsoft's Publish to web /view?r=… URL.");
      if ([...url.searchParams.keys()].some((key) => !["r", "pageName", "language", "embedImagePlaceholder"].includes(key)))
        throw new Error("The public URL contains an unsupported parameter; copy its generated iframe source.");
    } else {
      const guid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
      if (url.pathname !== "/reportEmbed" || !guid.test(url.searchParams.get("reportId") ?? ""))
        throw new Error("Secure mode requires Microsoft's Website or portal /reportEmbed?reportId=… URL.");
      if (url.searchParams.has("autoAuth") && url.searchParams.get("autoAuth") !== "true")
        throw new Error("The generated secure URL must keep autoAuth=true when supplied.");
      for (const key of ["ctid", "groupId"]) if (url.searchParams.has(key) && !guid.test(url.searchParams.get(key)!))
        throw new Error(`The secure URL has an invalid ${key}.`);
      if ([...url.searchParams.keys()].some((key) => !["reportId", "autoAuth", "ctid", "groupId", "pageName", "navContentPaneEnabled", "filterPaneEnabled"].includes(key)))
        throw new Error("The secure URL contains an unsupported parameter; copy its generated iframe source.");
    }
    return { url: url.toString(), error: null };
  } catch (error) {
    return { url: null, error: error instanceof Error ? error.message : "Invalid Power BI embed URL." };
  }
}

export const SNAPSHOT_COLUMNS: Record<SnapshotTable, string[]> = {
  hires: ["hire_id", "name", "role_title", "department", "start_date", "work_arrangement", "manager_id", "coordinator_id", "reviewer_id", "reviewer_name", "lifecycle", "demo", "created_at", "preparation_version", "required_tasks", "completed_required_tasks", "readiness_state", "at_risk", "signoff_valid", "current_approval_id", "approver_id", "approver_name", "approved_at", "review_episode_id", "review_entered_at", "review_wait_hours", "snapshot_at"],
  tasks: ["task_id", "hire_id", "template_key", "title", "team_id", "owner_id", "owner_name", "due_date", "required", "status", "blocked", "blocker_reason", "overdue", "dependency_ids", "evidence_note", "created_at", "completed_at", "completed_by_name", "completion_hours", "snapshot_at"],
  teams: ["team_id", "team_name"],
  review_episodes: ["review_episode_id", "hire_id", "preparation_version", "entered_at", "ended_at", "outcome", "wait_hours", "turnaround_hours", "snapshot_at"],
  approval_history: ["approval_id", "hire_id", "reviewer_id", "reviewer_name", "approved_at", "preparation_version", "invalidated_at", "invalidation_reason", "currently_valid", "snapshot_at"],
  metadata: ["schema_version", "snapshot_at", "business_date", "business_timezone", "risk_window_days", "hire_count", "task_count", "data_scope"],
};

export function createSnapshot(data: WorkspacePayload) {
  const hires: Row[] = data.hires.map((hire) => {
    const readiness = hireReadiness(hire);
    const approval = currentApproval(hire);
    const signoffValid = hire.lifecycle === "active" && readiness === "ready";
    const episode = hire.reviewEpisodes.filter((item) => !item.endedAt && item.preparationVersion === hire.preparationVersion)
      .sort((a, b) => b.enteredAt.localeCompare(a.enteredAt))[0];
    return { hire_id: hire.id, name: hire.name, role_title: hire.roleTitle, department: hire.department, start_date: hire.startDate,
      work_arrangement: hire.workArrangement, manager_id: hire.managerId, coordinator_id: hire.coordinatorId, reviewer_id: hire.reviewerId,
      reviewer_name: hire.reviewerName, lifecycle: hire.lifecycle, demo: hire.demo, created_at: hire.createdAt, preparation_version: hire.preparationVersion,
      required_tasks: hire.tasks.filter((task) => task.required).length,
      completed_required_tasks: hire.tasks.filter((task) => task.required && task.status === "completed").length,
      readiness_state: readiness, at_risk: hireAtRisk(hire, data.businessDate), signoff_valid: signoffValid,
      current_approval_id: approval?.id ?? null, approver_id: approval?.reviewerId ?? null, approver_name: approval?.reviewerName ?? null, approved_at: approval?.approvedAt ?? null,
      review_episode_id: episode?.id ?? null, review_entered_at: episode?.enteredAt ?? null,
      review_wait_hours: readiness === "awaiting_review" && episode ? elapsedHours(episode.enteredAt, data.now) : null, snapshot_at: data.now };
  });
  const tasks: Row[] = data.hires.flatMap((hire) => hire.tasks.map((task) => ({ task_id: task.id, hire_id: hire.id,
    template_key: task.templateKey, title: task.title, team_id: task.team, owner_id: task.assigneeId, owner_name: task.assigneeName,
    due_date: task.dueDate, required: task.required, status: task.status, blocked: taskBlocked(task, hire.tasks), blocker_reason: task.blocker,
    overdue: taskOverdue(task, data.businessDate), dependency_ids: task.dependencies.join(";"), evidence_note: task.note, created_at: task.createdAt,
    completed_at: task.completedAt, completed_by_name: task.completedByName, completion_hours: task.status === "completed" && task.completedAt && task.completedAt <= data.now
      ? elapsedHours(task.createdAt, task.completedAt) : null, snapshot_at: data.now })));
  const teams: Row[] = Object.entries(TEAM_NAMES).map(([team_id, team_name]) => ({ team_id, team_name }));
  const review_episodes: Row[] = data.hires.flatMap((hire) => hire.reviewEpisodes.map((episode) => ({ review_episode_id: episode.id,
    hire_id: hire.id, preparation_version: episode.preparationVersion, entered_at: episode.enteredAt, ended_at: episode.endedAt,
    outcome: episode.outcome, wait_hours: !episode.endedAt ? elapsedHours(episode.enteredAt, data.now) : null,
    turnaround_hours: episode.outcome === "approved" && episode.endedAt ? elapsedHours(episode.enteredAt, episode.endedAt) : null,
    snapshot_at: data.now })));
  const approval_history: Row[] = data.hires.flatMap((hire) => hire.approvals.map((approval) => ({ approval_id: approval.id,
    hire_id: hire.id, reviewer_id: approval.reviewerId, reviewer_name: approval.reviewerName, approved_at: approval.approvedAt, preparation_version: approval.preparationVersion,
    invalidated_at: approval.invalidatedAt, invalidation_reason: approval.reason,
    currently_valid: hire.lifecycle === "active" && hireReadiness(hire) === "ready" && currentApproval(hire)?.id === approval.id,
    snapshot_at: data.now })));
  const metadata: Row[] = [{ schema_version: "1", snapshot_at: data.now, business_date: data.businessDate, business_timezone: "Asia/Manila",
    risk_window_days: 3, hire_count: hires.length, task_count: tasks.length, data_scope: "All authorized hires, including cancelled; filter lifecycle=active for operational measures." }];
  return { schemaVersion: 1, snapshotAt: data.now, businessDate: data.businessDate, tables: { hires, tasks, teams, review_episodes, approval_history, metadata } };
}

export type ReportingSnapshot = ReturnType<typeof createSnapshot>;

export function csvSerialize(rows: Row[], columns: string[]): string {
  const cell = (value: Cell | undefined) => {
    if (value === null || value === undefined) return "";
    // Quote every string. Neutralize spreadsheet formulas without altering ordinary values.
    const raw = typeof value === "string" && /^(\s*[=+\-@]|[\t\r\n])/.test(value) ? `'${value}` : String(value);
    return `"${raw.replaceAll('"', '""')}"`;
  };
  return `${columns.map(cell).join(",")}\r\n${rows.map((row) => columns.map((key) => cell(row[key])).join(",")).join("\r\n")}${rows.length ? "\r\n" : ""}`;
}

export function snapshotCsv(snapshot: ReportingSnapshot, table: SnapshotTable): string {
  return csvSerialize(snapshot.tables[table], SNAPSHOT_COLUMNS[table]);
}
